name: Cross compile
on: [push]

jobs:
  build:
    name: Compile
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest] # https://help.github.com/ja/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dart
      - if: matrix.os == 'windows-latest'
        run: |
          choco install dart-sdk
          pub get
      - if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install dart
          pub get
      - if: matrix.os == 'macos-latest'
        run: |
          brew tap dart-lang/dart
          brew install dart
          pub get
