name: Cross compile
on: [push]

jobs:
  build:
    name: Compile
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest] # https://help.github.com/ja/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dart(windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install dart-sdk
          call refreshenv
      - name: Install Dart(ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https
          sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
          sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
          sudo apt-get update
          sudo apt-get install dart
          dpkg -L dart
          echo 'export PATH="$PATH:/usr/lib/dart/bin"' >> ~/.profile
      - name: Install Dart(macos)
        if: matrix.os == 'macos-latest'
        run: |
          brew tap dart-lang/dart
          brew install dart
      - name: Build
        run: |
          pub get
          dart2native bin/main.dart
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: result
          path: bin/main.exe
  execute:
    name: Run native code
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest] # https://help.github.com/ja/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: result
      - name: Run(windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd bin
          main.exe
      - name: Run(ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd bin
          main.exe
      - name: Run(macos)
        if: matrix.os == 'macos-latest'
        run: |
          cd bin
          main.exe
